In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A

array([ 1.04548297, -0.60277587, -1.00625998,  2.06446671,  1.64145644,
       -1.5925574 , -1.01693064, -0.9051568 , -0.0927714 ,  0.37583469])

In [9]:
B = np.random.randn(10)

In [11]:
B

array([ 1.04946831,  0.38091132,  0.37088251, -0.16250169, -0.421409  ,
        0.54614682,  0.86977659,  1.1036985 , -1.07504072,  2.17543854])

In [10]:
np.add(A,B)

array([ 2.09495128, -0.22186455, -0.63537747,  1.90196502,  1.22004744,
       -1.04641058, -0.14715406,  0.19854169, -1.16781212,  2.55127323])

In [12]:
np.maximum(A,B)

array([ 1.04946831,  0.38091132,  0.37088251,  2.06446671,  1.64145644,
        0.54614682,  0.86977659,  1.1036985 , -0.0927714 ,  2.17543854])